language: generic

services:
  - docker

cache:
  directories:
    - $HOME/.ccache

env:
  global:
    - ROS_DISTRO="melodic"
    - ROS_REPO=ros
    - CCACHE_DIR=$HOME/.ccache
    # travis build will time out with no output unless we use verbose output
    - VERBOSE_OUTPUT=true
    - VERBOSE_TESTS=true
  matrix:
    - OS_NAME=ubuntu OS_CODE_NAME=bionic
    - OS_NAME=debian OS_CODE_NAME=stretch

install:
  - git clone --quiet --depth 1 https://github.com/ros-industrial/industrial_ci.git .industrial_ci
script:
  - travis_wait 40 .industrial_ci/travis.sh
